nvironment: "dev"

spark:
  # Spark configurations
  spark.sql.shuffle.partitions: 200
  spark.serializer: org.apache.spark.serializer.KryoSerializer
  spark.sql.catalog.myGlueCatalog: org.apache.iceberg.spark.SparkCatalog
  spark.sql.catalog.myGlueCatalog.catalog-impl: org.apache.iceberg.aws.glue.GlueCatalog
  spark.sql.catalog.myGlueCatalog.warehouse: s3a://iceberg-mentorhub/
  spark.sql.catalog.myGlueCatalog.io-impl: org.apache.iceberg.aws.s3.S3FileIO
  # etc.

tables:
  # DB + table references
  transactions_raw: "dev.transactions_raw"
  merchants_raw: "dev.merchants_raw"
  users_raw: "dev.users_raw"
  compliance_raw: "dev.compliance_raw"

paths:
  # S3 or local paths for reading/writing
  inputBaseDir:  "s3a://my-bucket/data/inputs"
  outputBaseDir: "s3a://my-bucket/data/outputs"

partitions:
  # We can define partition columns or logic
  transactions: "processing_date"
  merchants:    "ingest_date"