apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-role-binding2
  namespace: serving-offline
subjects:
- kind: ServiceAccount
  name: serving-offline-account
  namespace: serving-offline
roleRef:
  kind: Role
  name: web-role
  apiGroup: rbac.authorization.k8s.io
